In [9]:
from IMDb_cleaner import IMDbPreprocessor
obj = IMDbPreprocessor()
X, y = obj.preprocess('IMDB Dataset.csv')

In [12]:
from rich import print
print (type(X))

<class 'numpy.ndarray'>

In [13]:
print(X[1:10])
print(X[0].__len__())

[[141 142 143 ...   0   0   0]
 [207 141 208 ...   0   0   0]
 [275 276 277 ...   0   0   0]
 ...
 [ 24 494 495 ...   0   0   0]
 [539 540 541 ...   0   0   0]
 [305 521 572 ...   0   0   0]]

1420

In [14]:
print(y[:10])
print(y.__len__())
print(X.__len__())

[1, 1, 1, 0, 1, 1, 1, 0, 0, 1]

50000

50000